name: CD

on:
  pull_request:
    types:
      - closed

  pull_request_review:
    types:
      - submitted
  

jobs:
  if_merged:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]' twine wheel

      - name: Set ENV variables
        run: |
          BRANCH_NAME=automated_release_branch_${{ github.head_ref || github.ref_name }}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          MAIN_BRANCH="protected_main"
          echo "MAIN_BRANCH=$MAIN_BRANCH" >> $GITHUB_ENV  

      - name: Configure git
        run: |
          git config --global user.email "github-actions@ploomber.io"
          git config --global user.name "github-actions"

      - name: Create a new branch and bump up tag version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MAIN_BRANCH=${{ env.MAIN_BRANCH }}
          BRANCH_NAME=${{ env.BRANCH_NAME }}

          echo "Pulling latest version from : $MAIN_BRANCH"
          git pull origin $MAIN_BRANCH

          echo "Creating a new branch : $BRANCH_NAME"
          git branch $BRANCH_NAME
          echo "SWITCH $BRANCH_NAME"
          git switch $BRANCH_NAME          

          pkgmt version --yes --no-push
          
          TAG=$(git describe --abbrev=0)

          echo "TAG=$TAG" >> $GITHUB_ENV
          
          echo "Running git add"
          git add .

          echo "Adding a commit"
          git commit --allow-empty -m "updates version"

          echo "Pushing changes to : $BRANCH_NAME"
          git push origin $BRANCH_NAME

      - name: Create a new PR for release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ env.TAG }}

          gh pr create -B $MAIN_BRANCH --title "Automated PR Release - $TAG" -l "release" -r ploomber-bot --body "Automated PR to release a new version to PyPI"


  if_approved:
    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          ref: ${{ github.ref_name }}

      - name: Set ENV variables
        run: |
          BRANCH_NAME=automated_release_branch_${{ github.head_ref || github.ref_name }}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          MAIN_BRANCH="protected_main"
          echo "MAIN_BRANCH=$MAIN_BRANCH" >> $GITHUB_ENV  
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]' twine wheel
          
      - name: Configure git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

      - name: Test TAG to push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          git pull origin protected_main --rebase 

          TAG=$(git describe --abbrev=0)
          echo "tag to push : $TAG"